server:
  port: 8081

spring:
  application:
    name: task
  data:
      mongodb:
        uri: mongodb://localhost:27017/task_db

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080 # URL Auth Server

  kafka:
    bootstrap-servers: localhost:9092
